# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EngineeringImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('external_src', models.URLField()),
                ('local_src', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='EngineeringProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('category', models.ManyToManyField(to='api.Category')),
                ('image', models.ManyToManyField(to='api.EngineeringImage')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('src', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('external_src', models.URLField()),
                ('local_src', models.FileField(upload_to=b'')),
                ('camera', models.CharField(max_length=200)),
                ('exposure', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('category', models.ManyToManyField(to='api.Category')),
                ('image', models.ManyToManyField(to='api.PhotoImage')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=50)),
                ('category', models.ManyToManyField(to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('src', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='photoproject',
            name='skill',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AddField(
            model_name='photoproject',
            name='tool',
            field=models.ManyToManyField(to='api.Tool'),
        ),
        migrations.AddField(
            model_name='photoproject',
            name='video',
            field=models.ManyToManyField(to='api.Video'),
        ),
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.ManyToManyField(to='api.PhotoImage'),
        ),
        migrations.AddField(
            model_name='engineeringproject',
            name='skill',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AddField(
            model_name='engineeringproject',
            name='tool',
            field=models.ManyToManyField(to='api.Tool'),
        ),
        migrations.AddField(
            model_name='engineeringproject',
            name='video',
            field=models.ManyToManyField(to='api.Video'),
        ),
    ]
