# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringimage',
            name='external_src',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='engineeringimage',
            name='local_src',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='engineeringproject',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='engineeringproject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='engineeringproject',
            name='image',
            field=models.ManyToManyField(blank=True, to='api.EngineeringImage'),
        ),
        migrations.AlterField(
            model_name='engineeringproject',
            name='skill',
            field=models.ManyToManyField(blank=True, to='api.Skill'),
        ),
        migrations.AlterField(
            model_name='engineeringproject',
            name='tool',
            field=models.ManyToManyField(blank=True, to='api.Tool'),
        ),
        migrations.AlterField(
            model_name='engineeringproject',
            name='video',
            field=models.ManyToManyField(blank=True, to='api.Video'),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ManyToManyField(blank=True, to='api.PhotoImage'),
        ),
        migrations.AlterField(
            model_name='link',
            name='src',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='photoimage',
            name='camera',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photoimage',
            name='exposure',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photoimage',
            name='external_src',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='photoimage',
            name='local_src',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='image',
            field=models.ManyToManyField(blank=True, to='api.PhotoImage'),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='skill',
            field=models.ManyToManyField(blank=True, to='api.Skill'),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='tool',
            field=models.ManyToManyField(blank=True, to='api.Tool'),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='video',
            field=models.ManyToManyField(blank=True, to='api.Video'),
        ),
    ]
