# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180213_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.Category'),
        ),
    ]
