# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180207_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoImage',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='PhotoProject',
            new_name='Project',
        ),
        migrations.RemoveField(
            model_name='engineeringproject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='engineeringproject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='engineeringproject',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='engineeringproject',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='engineeringproject',
            name='video',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.DeleteModel(
            name='EngineeringImage',
        ),
        migrations.DeleteModel(
            name='EngineeringProject',
        ),
    ]
