# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.Category'),
        ),
    ]
