# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180216_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='category',
        ),
    ]
