# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180216_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='local_src',
            new_name='src',
        ),
    ]
