# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180216_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='headline',
        ),
    ]
