# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180216_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.RemoveField(
            model_name='link',
            name='image',
        ),
        migrations.RemoveField(
            model_name='link',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='video',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
