# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180226_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('src', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.ManyToManyField(blank=True, to='api.Link'),
        ),
    ]
