# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180304_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
    ]
