# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_project_preview_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2500)),
            ],
        ),
    ]
