# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180316_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gallery'),
        ),
    ]
