# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_project_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
